### ISSUE TITLE
Composition Editor crashes on Startup

### ISSUE THREAD

**Issue by Joltrix** [Starcounter/CompositionEditor#34]
### Steps to reproduce
Composition Editor Startup

### Expected result
It should start, and should then be usable within the other apps running.

### Actual result
Composition Editor crashes when executed.

### Technical information
```
ScErrServerCommandFailed (SCERR10011): The operation "Starting CompositionEditor in default" failed.
Version: 2.3.1.6981.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.
```

```
Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. , PID=840, Database=default
Version: 2.3.1.6981.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10007.
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=10007
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10007
---> Starcounter.DbException: ScErrProcessExitCodeNotAvailable (SCERR10040): The exit code of the terminating process was not available.
Version: 2.3.1.6981.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10040.
ErrorCode=10040
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10040
```

##### Starcounter version 
2.3.1.6981

##### Involved apps' version
It doesn't really matter. The Composition Editor crashes even when it's by itself.
 
##### Browsers affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

Most likely the other browsers as well, but I just tried those three.
### Screenshot
![compositioneditorcrash](https://user-images.githubusercontent.com/10708580/29276138-ec177b40-810d-11e7-96df-d8f66cb9e22b.gif)

**Comment by Joltrix** [comment]
cc @warpech 

I suspect this might have something to do with the Starcounter version. @bouguila who is running an older version of Starcounter does not have any issues with the Composition Editor

**Comment by warpech** [comment]
I can't reproduce it anymore. Please reopen if occurs again. Thanks for reporting!
